model:
  name: r3d_18

task:
  name: moving_mnist_demo
  finished:
    max_steps: 100_000
  dataloader:
    train:
      batch_size: 16

optimizer:
  name: adamw

lr_scheduler:
  name: linear

trainer:
  name: ddp

logger:
  - name: stdout
  - name: tensorboard
